debug: true

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
spring:
  liquibase:
    enabled: false
  r2dbc:
    url: r2dbc:mariadb://localhost:3306
    username: test
    password: test
open-ai:

